#!/bin/sh
#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.

# Change your keymap:
xmodmap "/home/cabrito/.Xmodmap"

# Applications you want to run with fluxbox.
# MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN ''&'' AT THE END.
#
# unclutter -idle 2 &
# wmnd &
# wmsmixer -w &
# idesk &
chromium-browser &
gnome-terminal --role=term1 &
gnome-terminal --role=term2 &
gnome-terminal --role=term3 &
gnome-terminal --role=term4 &
gnome-terminal --role=term5 &
gnome-terminal --role=term6 &
gnome-terminal --role=term7 &
gnome-terminal --role=term8 &
gnome-terminal --role=term9 &
keepass2 &
xscreensaver &
#
# Debian-local change:
#   - fbautostart has been added with a quick hack to check to see if it
#     exists. If it does, we'll start it up by default.
which fbautostart > /dev/null
if [ $? -eq 0 ]; then
    fbautostart
fi

# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.

exec fluxbox
# or if you want to keep a log:
# exec fluxbox -log "/home/cabrito/.fluxbox/log"
